"""users table

Revision ID: 682f6e91db9a
Revises: 56a14a858e84
Create Date: 2018-10-30 21:38:00.834294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '682f6e91db9a'
down_revision = '56a14a858e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_name', table_name='user')
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.drop_index('ix_user_saldo', table_name='user')
    op.create_index(op.f('ix_user_saldo'), 'user', ['saldo'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_saldo'), table_name='user')
    op.create_index('ix_user_saldo', 'user', ['saldo'], unique=1)
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.create_index('ix_user_name', 'user', ['name'], unique=1)
    # ### end Alembic commands ###
